// <auto-generated />
namespace MeeSoftetchWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AppliedFor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppliedFor));
        
        string IMigrationMetadata.Id
        {
            get { return "201403171741227_AppliedFor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
